ss

diff --git a/ors.init b/ors.init
--- a/ors.init
+++ b/ors.init
@@ -1,27 +1,107 @@
 #!/bin/sh
 
-CONFIG=/etc/marketcetera/ors.conf
-[ -f $CONFIG ] && . $CONFIG
+CONFIG="/etc/marketcetera/ors.conf"
+[ -r $CONFIG ] && . $CONFIG
 
-CLASSPATH="${ORS_DIR}/conf"
-for jar in `find "${METC_HOME}/lib" -name *.jar`; do
-  CLASSPATH=$CLASSPATH:$jar
-done
+PIDFILE=$RUN_DIR/ors.pid
 
-CMD=`which java`
-cat > $USER_PROPERTIES_FILE << EOF
-metc.ws.host=${WS_HOST}
-metc.ws.port=${WS_PORT}
-metc.jms.broker.url=tcp://\${metc.ws.host}:${ACTIVEMQ_PORT}?wireFormat.maxInactivityDurationInitalDelay=30000
-metc.jdbc.user=${DB_USER}
-metc.jdbc.password=${DB_PASS}
-metc.jdbc.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?logSlowQueries=true&$query
-EOF
+function isrunning() {
+  if [ -f $PIDFILE ]; then
+    local pid=$(cat $PIDFILE 2> /dev/null)
+    uid=$(id -u)
+    if `ps --pid $pid -u $uid 2>&1 | grep $pid > /dev/null 2>&1`; then
+      return 0
+    fi
+  fi
+  return 1
+}
 
-CMD="$CMD -classpath $CLASSPATH"
-# This argument have to be set before main class
-CMD="$CMD -Dorg.marketcetera.appDir=${ORS_DIR}" 
-CMD="$CMD org.marketcetera.ors.OrderRoutingSystem" 
-CMD="$CMD $@"
-exec $CMD
+# Kill the process given by $1 and its children
+killtree() {
+  local _pid=$1
+  for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
+    killtree ${_child}
+  done
+
+  local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+  if [ -z "$should_be_gone_pid" ]; then
+    return
+  else
+    kill -TERM ${_pid}
+  fi
+
+  local count=0
+  while [ ${count} -lt 15 ]; do
+    local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+    if [ -z "$should_be_gone_pid" ]; then
+      return
+    else
+      sleep 2
+      let count=${count}+1
+    fi
+  done
+
+  local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+  if [ ! -z $should_be_gone_pid ]; then
+    kill -9 ${_pid}
+  fi
+}
+
+function start() {
+  echo "Starting ORS"
+  if ! isrunning; then
+    /usr/bin/ors2 >/dev/null 2>&1 &
+    local pid=$!
+    echo $pid > $PIDFILE
+    echo "Started ORS"
+  else
+    echo "ORS already running" 1>&2
+  fi
+}
+
+function stop() {
+  echo "Stopping ORS"
+
+  if isrunning; then
+    if [ -f "$PIDFILE" ]; then
+      pid=$(cat $PIDFILE);
+      killtree $pid
+      echo "Stopped ORS"  
+    else
+      echo "Failed to locate ORS PID File" 1>&2
+    fi
+  else
+    echo "ORS was already stopped"
+  fi
+}
+
+function restart() {
+  stop
+  start
+}
+
+function status() {
+  if isrunning; then
+    echo "ORS is running"
+  else
+    echo "ORS is not running"
+  fi
+}
+
+function usage() {
+   echo "Usage: $0 {start|stop|restart|status}"
+   RETVAL="2"
+}
+
+# See how we were called.
+RETVAL="0"
+case "$1" in
+    start) start ;;
+    stop) stop ;;
+    restart) restart ;;
+    status) status ;;
+    *) usage ;;
+esac
+
+exit $RETVAL
 
